version: '3.7'
services:
  frontend:
    image: "vvnifontov/dormitory:0.0.100"
    build: ./dormitory-app
    ports:
      - '5173:5173'
    volumes:
      - /dormitory-app/node_modules:/usr/app/node_modules
      - ./dormitory-app:/usr/app
  backend:
    image: 'm00nnnn/myfirstrepository:0.0.96'
    build:
      context: .
    expose:
      - "8080"
    ports:
      - "8080:8080"
    container_name: backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dormitory
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: 'postgres'
    container_name: db
    environment:
      - POSTGRES_DB=dormitory
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"