spring:
  application:
    name: dormitory-api
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  sql:
    init:
      mode: always
security:
  jwt:
    token:
      secret-key: secret