spring:
  application:
    name: dormitory-api
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
  sql:
    init:
      mode: always
security:
  jwt:
    token:
      secret-key: secret