create table app_user(
    id int primary key generated by default as identity,
    role varchar not null,
    login varchar not null unique,
    password varchar not null
);
create table photo(
    id int primary key generated by default as identity,
    mime_type varchar,
    data bytea
);
create table commandant(
    id int primary key generated by default as identity,
    firstname varchar not null,
    lastname varchar not null,
    middlename varchar,
    phone varchar not null unique,
    email varchar not null unique,
    photo_id int not null unique references photo(id),
    user_id int unique references app_user(id)
);
create table floor(
    id int primary key generated by default as identity,
    number varchar not null unique
);
create table room(
    id int primary key generated by default as identity,
    number varchar not null unique,
    floor_id int references Floor(id),
    max_count_student int not null
);
create table room_inventory(
    id int primary key generated by default as identity,
    inventory_type varchar not null,
    code varchar not null unique,
    room_id int references Room(id)
);
create table student(
    id int primary key generated by default as identity,
    student_id varchar not null unique,
    firstname varchar not null,
    lastname varchar not null,
    middlename varchar,
    phone varchar not null unique,
    email varchar unique,
    photo_id int references photo(id),
    gender varchar not null,
    room_id int references Room(id),
    user_id int unique references app_user(id)
);
create table document(
    id int primary key generated by default as identity,
    student_id int references Student(id),
    type varchar not null,
    mime_type varchar not null,
    data bytea not null
);
create table inventory(
    id int primary key generated by default as identity,
    student_id int references Student(id),
    type varchar not null
);
create table receipt(
    id int primary key generated by default as identity,
    student_id int references Student(id),
    date date not null,
    data varchar not null
);
create table check_(
    id int primary key generated by default as identity,
    date date not null,
    data varchar not null,
    receipt_id int unique references Receipt(id)
)